annotations:
  artifacthub.io/changes: |-
    - kind: changed
      add via-ferrata-app backend 
apiVersion: v2
dependencies:
  - name: common
    repository: https://zekker6.github.io/helm-charts
    version: 0.5.2
description: via-ferrata-app helm package
home: https://github.com/zekker6/helm-charts/tree/master/charts/apps/chartdb
# icon: https://www.chartdb.co/favicon-32x32.png
kubeVersion: ">=1.16.0-0"
maintainers:
  - name: "zekker6"
    email: "me@zekker.dev"
    url: "https://github.com/zekker6/"
# sources:
  # - https://github.com/chartdbco/chartdb
  # - https://github.com/zekker6/helm-charts/tree/master/charts/apps/chartdb

name: via-ferrata-backend

# It is recommended to use it with quotes.
appVersion: "1.0.0"

version: 0.0.1